version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: pi4
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./charts.d.conf:/etc/netdata/charts.d.confz
    environment: 
      PGID: 998
    restart: unless-stopped
    #command: -W set 'netdata.config' 'sensors' 'force'

